{% set name = "topoflow-evap-read-file-csdms" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Evaporation-Read_File
  license: Apache
  summary: |
    The EvapReadFile component, a part of the spatially
    distributed hydrologic model TopoFlow, provides a way for reading in
    parameters for the evaporation process.
